### ISSUE TITLE
Create ggplot gallery

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#34]
This will probably be in a separate repo (in which case we'll move this issue). Oskar to send latest data viz guidelines and then we'll get started.

<sub>[R-35](https://linear.app/rfortherestofus/issue/R-35/create-ggplot-gallery)</sub>

**Comment by OskaratOmni** [comment]
@dgkeyes , I finally started reviewing the draft ggplot gallery. Unfortunately it is not as far along as I'd hoped. It needs a lot of work and even the plots that are there aren't quite consistent with our own guidelines. I'll see what I can do. I'm not sure if I should just turn it over to you in a ... less-complete-than-we'd-hoped state or try to work on it more this week. More soon. This is just an update.

**Comment by dgkeyes** [comment]
I do think having you give it to us once it's ready is the best approach.

**Comment by dgkeyes** [comment]
Ok, I've reviewed all of the docs. @tvroylandt [I recorded a video to show you what I'm thinking with this](https://show.rfor.us/LZgV2D6j). Do you want to work on creating a draft of a "Data Visualization Principles" vignette based on what I show in the video?

**Comment by OskaratOmni** [comment]
Hey @dgkeyes  and @tvroylandt , it turns out that putting together a proper draft of this is really a lot of work. What I propose is that you review the first few sections, up through 'bar graphs'. You will see that I put a note in brackets in the rmd file saying something like 'Hey David and Thomas, only review up to this point.' I will explain more in a video shortly. 

I added you both as collaborators to this repo: https://github.com/OMNI-Institute-QuantBPT/OMNI-ggplot-gallery

**Comment by OskaratOmni** [comment]
@dgkeyes  and @tvroylandt  the document for you to review is called: OMNI_ggplot_gallery_main_forDT.rmd
where DT ~ David and Thomas. 

And again just up until the note after the stacked bar graph.

**Comment by dgkeyes** [comment]
Sounds good, thanks!

**Comment by tvroylandt** [comment]
Thanks. I created a PR by duplicating the files and added comments here : https://github.com/OMNI-Institute-QuantBPT/OMNI-ggplot-gallery/pull/1/files#diff-5158ac4e46b311a0016b820b5575fc19907cba7c7f6d6738453eee920491e797

**Comment by tvroylandt** [comment]
Don't worry about the mess, this is a great work !

**Comment by OskaratOmni** [comment]
Also, don't feel any obligation to preserve any of the ggplot code that is there. We grabbed this code randomly from several projects scattered across the last several years at OMNI. There is nothing special about it, per se. It is only a suggestion for how to achieve the output in some cases. 

@tvroylandt , I'm not sure if you are aware of this yet, but the majority of data viz at OMNI is done in excel. Typically, one of us on the quantitative team makes some tables and then hands the tables off to a quite junior staff person on the data viz team who makes the visuals in excel, which are then copy-pasted into word or powerpoint. Obviously, there is great room for improved efficiency with that workflow and I'm really hoping that this ggplot gallery can help.

**Comment by tvroylandt** [comment]
@OskaratOmni, in the PR, I've started to create a custom guide from your excellent start. For that I use Quarto listings so that the first page could be general guidances and the rest could be a real gallery.

This will also help people to find what's best for them without to be feared by a big guide at once. This is obviously a very work in progress and I will continue to make the gallery one plot after another (as an example, pie chart, donut chart, slopegraph and diverging bar chart are ok). I'll let you know when the PR is ready.

You can render the WIP website by clicking on "Render website" in your "Build" panel in RStudio.
