### ISSUE TITLE
omni logo path on word template

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#53]
Hey @tvroylandt, I was using the word template to test the table function, and I noticed that there is an error when it tries to load the image. 

```{r, fig.cap = "Title", out.width="200px", fig.align='center', out.extra='data-prefix="Figure"'}
knitr::include_graphics(system.file("assets/omni_rmd_template/images/example_figure.png", package = "omni"))
```

which generates:
Error in knitr::include_graphics(system.file("assets/omni_rmd_template/images/example_figure.png",  : 
  Cannot find the file(s): ""

For my own education I would love to know how the package places an image in a system.file. Is that something you can do in the package settings? Probably that is complicated to explain so fine to ignore the 'how to' part of this. :-P

**Comment by tvroylandt** [comment]
Oh yes I cleaned up all the paths but forgot this one inside the template.

In fact, in a package, `system.file` just found things that are in the `inst` folder. The rest is just the path, starting in this folder.
But you should also be careful not to have too much there because it's installed in this folder, otherwise the package will become heavy.

**Comment by tvroylandt** [comment]
This one has been solved by the way
